version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: pacbook-store-data
    environment:
      POSTGRES_DB: pacbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5436:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
